<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
        <!-- Handmatige hogere versie. Kan weg wanneer Microsoft.EntityFrameworkCore.Sqlite geen dependency meer heeft op SQLitePCLRaw.bundle_e_sqlite3 2.1.11 -->
        <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Business.Components\Business.Components.csproj" />
        <ProjectReference Include="..\Common.Common\Common.Common.csproj" />
        <ProjectReference Include="..\Data.Repository\Data.Repository.csproj" />
    </ItemGroup>

</Project>
