name: PhotographyApi-cd-pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual trigger' 

jobs:
  apply-secrets:
    environment:
      name: production

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: microsoft/variable-substitution@v1 
        with:
          files: '${{ inputs.api-name }}/appsettings.Production.json'
        env:
          AppSettings.RiesjApiKey: ${{ secrets.RIESJ_API_KEY }}
          AppSettings.JwtSecret: ${{ secrets.JWT_SECRET_KEY }}
          AppSettings.MapboxPublicToken: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
          AppSettings.GarminExploreRawKmlFeed: ${{ secrets.GARMIN_EXPLORE_RAW_KML_FEED }}

  build-test-publish:
    uses: richardjanssen/SharedWorkflows/.github/workflows/dotnet-api-build-test-publish.yml@main
    with:
      api-name: PhotographyApi
      
  deploy-run:
    needs: build-test-publish
    uses: richardjanssen/SharedWorkflows/.github/workflows/linux-vps-deploy-run-v2.yml@main
    with:
      application-name: PhotographyApi
      is-service: true
    secrets:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      ssh-key: ${{ secrets.SSHKEY }}
      ssh-passphrase: ${{ secrets.SSHPASSPHRASE }}
