name: PhotographyApi-add-satellite-location

on:
  schedule:
    - cron:  '5,15,25,35,45,55 * * * *'

jobs:
  call-riesj-api:
    runs-on: ubuntu-latest
    steps:
    - name: Add satellite location
      id: addSatelliteLocationRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://riesj.com/api/v1/Location/AddSatelliteMessengerLocation'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "RiesjApiKey": "${{ secrets.RIESJ_API_KEY }}"}'
    - name: Show response
      run: |
        echo ${{ steps.addSatelliteLocationRequest.outputs.response }}
