name: PhotographyApi-cd-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-publish:
    uses: ./.github/workflows/dotnet-api-build-test-publish.yml
    with:
      api-name: PhotographyApi
      
  deploy-run:
    needs: build-test-publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create dist folder
      run: mkdir ~/dist
      
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: PhotographyApi
        path: dist
        
    - name: Copy artifact via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.SSHPASSPHRASE }}
        rm: false
        strip_components: 1
        source: "dist/*"
        target: "~/var/www/PhotographyApi2"

    - name: Start service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.SSHPASSPHRASE }}
        script: | 
          sudo systemctl start kestrel-photographyapi.service
          sudo systemctl status kestrel-photographyapi.service
