name: PhotographyApi-ci-pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test-publish:
    uses: richardjanssen/SharedWorkflows/.github/workflows/dotnet-api-build-test-publish.yml@main
    with:
      api-name: PhotographyApi
      do-upload: false