name: PhotographyApi-cd-pipeline

on:
  push:
    branches: [ main ]

jobs:
  checkout-substitute:
    uses: ./.github/workflows/PhotographyApi-variable-substitutions.yml
    
  build-test-publish:
    uses: richardjanssen/SharedWorkflows/.github/workflows/dotnet-api-build-test-publish-no-checkout.yml@main
    with:
      api-name: PhotographyApi
      
  deploy-run:
    needs: build-test-publish
    uses: richardjanssen/SharedWorkflows/.github/workflows/linux-vps-deploy-run.yml@main
    with:
      application-name: PhotographyApi
    secrets:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      ssh-key: ${{ secrets.SSHKEY }}
      ssh-passphrase: ${{ secrets.SSHPASSPHRASE }}
