name: PhotographyApi-cd-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-publish:
    uses: ./.github/workflows/dotnet-api-build-test-publish.yml
    with:
      api-name: PhotographyApi
    secrets:
      riesj-api-key: ${{ secrets.RIESJ_API_KEY }}
      jwt-secret-key: ${{ secrets.JWT_SECRET_KEY }}
      mapbox-public-token: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
      garmin-explore-raw-kml-feed: ${{ secrets.GARMIN_EXPLORE_RAW_KML_FEED }}
      
  deploy-run:
    needs: build-test-publish
    uses: richardjanssen/SharedWorkflows/.github/workflows/linux-vps-deploy-run.yml@main
    with:
      application-name: PhotographyApi
    secrets:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      ssh-key: ${{ secrets.SSHKEY }}
      ssh-passphrase: ${{ secrets.SSHPASSPHRASE }}
