name: .NET

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish PhotographyApi/PhotographyApi.csproj -c Release -o dist
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: PhotographyApi
        path: dist/**
        if-no-files-found: error

