name: PhotographyApi-cd-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-publish:
    uses: ./.github/workflows/dotnet-api-build-test-publish.yml
    with:
      api-name: PhotographyApi
    secrets:
      database-connection-string: ${{ secrets.DATABASE_CONNECTION_STRING }}
      jwt-secret-key: ${{ secrets.JWT_SECRET_KEY }}
      
  deploy-run:
    needs: build-test-publish
    uses: richardjanssen/SharedWorkflows/.github/workflows/linux-vps-deploy-run.yml@main
    with:
      application-name: PhotographyApi
    secrets:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      ssh-key: ${{ secrets.SSHKEY }}
      ssh-passphrase: ${{ secrets.SSHPASSPHRASE }}
