name: PhotographyApi CI-pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test-publish:
    uses: richardjanssen/SharedWorkflows/.github/workflows/dotnet-build.yml@main
    with:
      api-name: PhotographyApi
      release-build: false