name: PhotographyApi CD-pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual trigger'

jobs:
  dotnet-build:
    uses: richardjanssen/SharedWorkflows/.github/workflows/dotnet-build.yml@main
    with:
      app-name: 'PhotographyApi'
      release-build: true
      
  deploy:
    needs: dotnet-build
    uses: richardjanssen/SharedWorkflows/.github/workflows/ubuntu-vps-deploy.yml@main
    with:
      app-name: 'PhotographyApi'
      is-service: true
    secrets:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      ssh-key: ${{ secrets.SSHKEY }}
      ssh-passphrase: ${{ secrets.SSHPASSPHRASE }}